// Настоящая страница токена: график по минутам, потом лист покупки.
import { p, b } from "./lib.mjs";
const OUT = "/home/user/Facet_MiniApp/demo/promo/assets/scr";
await p.screenshot({ path: `${OUT}/home.png` });
await p.mouse.click(131, 752);
await p.waitForTimeout(2000);
await p.waitForTimeout(200);
await p.screenshot({ path: `${OUT}/pad.png` });
await p.getByText("Moon Cat", { exact: false }).first().click();
await p.waitForTimeout(4000);
console.log((await p.evaluate(() => document.body.innerText)).replace(/\n+/g, " | ").slice(0, 300));
await p.getByText(/^(1м|1m|1 мин)$/).first().click();
await p.waitForTimeout(2500);
await p.screenshot({ path: `${OUT}/token.png` });
await p.evaluate(() => { const x = [...document.querySelectorAll("button")].find((e) => e.textContent.trim() === "Купить"); x.click(); });
await p.waitForTimeout(2000);
await p.screenshot({ path: `${OUT}/buy.png` });
await p.getByText("5 GRAM", { exact: true }).first().click();
await p.waitForTimeout(1200);
await p.screenshot({ path: `${OUT}/buy5.png` });
console.log((await p.evaluate(() => document.body.innerText)).replace(/\n+/g, " | ").slice(0, 500));
await b.close();
